// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBauACjfWpoQYIXWXmYvx736T0-_Ax8J88',
    appId: '1:416061657158:web:2ccc790e879722ef01ba47',
    messagingSenderId: '416061657158',
    projectId: 'visata-58cf4',
    authDomain: 'visata-58cf4.firebaseapp.com',
    storageBucket: 'visata-58cf4.firebasestorage.app',
    measurementId: 'G-DMRKW8ZL3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvKjqUrZnnInRodrp9zCR1LokM69Dep8c',
    appId: '1:416061657158:android:e5feb798b8480fac01ba47',
    messagingSenderId: '416061657158',
    projectId: 'visata-58cf4',
    storageBucket: 'visata-58cf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAD3bYqTPh_Ds79U-DD5J47UjF6wBFfGs',
    appId: '1:416061657158:ios:a9002bb3bde9c8f901ba47',
    messagingSenderId: '416061657158',
    projectId: 'visata-58cf4',
    storageBucket: 'visata-58cf4.firebasestorage.app',
    iosBundleId: 'com.example.vistaprint24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAD3bYqTPh_Ds79U-DD5J47UjF6wBFfGs',
    appId: '1:416061657158:ios:a9002bb3bde9c8f901ba47',
    messagingSenderId: '416061657158',
    projectId: 'visata-58cf4',
    storageBucket: 'visata-58cf4.firebasestorage.app',
    iosBundleId: 'com.example.vistaprint24',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBauACjfWpoQYIXWXmYvx736T0-_Ax8J88',
    appId: '1:416061657158:web:299535227857bbef01ba47',
    messagingSenderId: '416061657158',
    projectId: 'visata-58cf4',
    authDomain: 'visata-58cf4.firebaseapp.com',
    storageBucket: 'visata-58cf4.firebasestorage.app',
    measurementId: 'G-LPGEGKNE68',
  );
}
